use clap::{Arg, Command};

pub fn build_user_commands() -> Command <'static> {
    Command::new("user")
        .subcommand(
            Command::new("ls")
                .about("List Matrix users")
                .arg(
                    Arg::new("deactivated")
                    .long("deactivated")
                    .short('d')
                    .action(clap::ArgAction::SetTrue)
                    .help("Include deactivated users from the search.")
                )
                .arg(
                    Arg::new("from")
                        .long("from")
                        .short('f')
                        .value_parser(clap::value_parser!(u64))
                        .default_value("0")
                        .takes_value(true)
                        .help("Offset in the returned list.")
                )
                .arg(
                    Arg::new("guests")
                    .long("no-guests")
                    .action(clap::ArgAction::SetFalse)
                    .help("Exclude guest users from the search.")
                )
                .arg(
                    Arg::new("limit")
                        .long("limit")
                        .short('l')
                        .value_parser(clap::value_parser!(u64))
                        .default_value("100")
                        .takes_value(true)
                        .help("Maximum amount of users to return.")
                )
                .arg(
                    Arg::new("name")
                        .long("name")
                        .short('n')
                        .takes_value(true)
                        .help("Filter users with user id or displaynames.")
                )
                .arg(
                    Arg::new("order_by")
                        .long("order_by")
                        .short('o')
                        .default_value("name")
                        .takes_value(true)
                        .value_parser([
                          "name", "is_guest", "admin", "user_type", "deactivated",
                          "shadow_banned", "displayname", "avatar_url", "creation_ts"
                        ])
                        .help("Sort the returned list of users.")
                )
                .arg(
                    Arg::new("user_id")
                    .long("user")
                    .short('u')
                    .takes_value(true)
                    .help("Filter users with only user id.")
                )
        )
        .subcommand(
            Command::new("show")
                .about("Show Matrix user details")
                .arg(
                    Arg::new("user_id")
                    .long("user")
                    .short('u')
                    .takes_value(true)
                    .required(true)
                    .help("User identifier")
                )
        )
        .subcommand(
            Command::new("deactivate")
                .about("Deactivate Matrix user")
                .arg(
                    Arg::new("user_id")
                    .long("user")
                    .short('u')
                    .takes_value(true)
                    .required(true)
                    .help("user identifier")
                )
        )
        .subcommand(
            Command::new("sessions")
                .about("Show Matrix user active sessions")
                .arg(
                    Arg::new("user_id")
                    .long("user")
                    .short('u')
                    .takes_value(true)
                    .required(true)
                    .help("user identifier")
                )
        )
        .subcommand(
            Command::new("isadmin")
                .about("Show if user is a server admin")
                .arg(
                    Arg::new("user_id")
                    .long("user")
                    .short('u')
                    .takes_value(true)
                    .required(true)
                    .help("user identifier")
                )
        )
        .subcommand(
            Command::new("promote")
                .about("Promote a user as server admin")
                .arg(
                    Arg::new("user_id")
                    .long("user")
                    .short('u')
                    .takes_value(true)
                    .required(true)
                    .help("user identifier")
                )
        )
        .subcommand(
            Command::new("retrograde")
                .about("Retrograde server admin privileges")
                .arg(
                    Arg::new("user_id")
                    .long("user")
                    .short('u')
                    .takes_value(true)
                    .required(true)
                    .help("user identifier")
                )
        )
        .subcommand(
            Command::new("rooms")
                .about("Show user joined rooms")
                .arg(
                    Arg::new("user_id")
                    .long("user")
                    .short('u')
                    .takes_value(true)
                    .required(true)
                    .help("user identifier")
                )
        )
        .subcommand(
            Command::new("accountdata")
                .about("Show user account data")
                .arg(
                    Arg::new("user_id")
                    .long("user")
                    .short('u')
                    .takes_value(true)
                    .required(true)
                    .help("user identifier")
                )
        )
        .subcommand(
            Command::new("medias")
                .about("Show user medias")
                .arg(
                    Arg::new("from")
                        .long("from")
                        .short('f')
                        .value_parser(clap::value_parser!(u64))
                        .default_value("0")
                        .takes_value(true)
                        .help("Offset in the returned list.")
                )
                .arg(
                    Arg::new("limit")
                        .long("limit")
                        .short('l')
                        .value_parser(clap::value_parser!(u64))
                        .default_value("100")
                        .takes_value(true)
                        .help("Maximum amount of medias to return.")
                )
                .arg(
                    Arg::new("user_id")
                    .long("user")
                    .short('u')
                    .takes_value(true)
                    .required(true)
                    .help("user identifier")
                )
                .arg(
                    Arg::new("order_by")
                        .long("order_by")
                        .short('o')
                        .default_value("created_ts")
                        .takes_value(true)
                        .value_parser([
                            "media_id", "upload_name", "created_ts", "last_access_ts",
                            "media_length", "media_type", "quarantined_by", "safe_from_quarantine"
                        ])
                        .help("Sort the returned list of medias.")
                )
        )
        .subcommand(
            Command::new("devices")
                .about("Show user devices")
                .arg(
                    Arg::new("device_id")
                    .long("device")
                    .short('d')
                    .takes_value(true)
                    .required(false)
                    .help("device identifier")
                )
                .arg(
                    Arg::new("user_id")
                    .long("user")
                    .short('u')
                    .takes_value(true)
                    .required(true)
                    .help("user identifier")
                )
        )
        .subcommand(
            Command::new("pushers")
                .about("Show user pushers")
                .arg(
                    Arg::new("user_id")
                    .long("user")
                    .short('u')
                    .takes_value(true)
                    .required(true)
                    .help("user identifier")
                )
        )
        .subcommand(
            Command::new("ban")
                .about("Shadow ban a user")
                .arg(
                    Arg::new("user_id")
                    .long("user")
                    .short('u')
                    .takes_value(true)
                    .required(true)
                    .help("user identifier")
                )
        )
        .subcommand(
            Command::new("unban")
                .about("Shadow unban a user")
                .arg(
                    Arg::new("user_id")
                    .long("user")
                    .short('u')
                    .takes_value(true)
                    .required(true)
                    .help("user identifier")
                )
        )
        .subcommand(
            Command::new("ratelimit")
                .about("Show user ratelimit details")
                .arg(
                    Arg::new("user_id")
                    .long("user")
                    .short('u')
                    .takes_value(true)
                    .required(true)
                    .help("user identifier")
                )
                .arg(
                    Arg::new("burst")
                        .long("burst-count")
                        .short('b')
                        .value_parser(clap::value_parser!(u64))
                        .takes_value(true)
                        .help("authorized actions before being limited")
                )
                .arg(
                    Arg::new("message")
                        .long("message-limit")
                        .short('m')
                        .value_parser(clap::value_parser!(u64))
                        .takes_value(true)
                        .help("number of actions limit in a second")
                )
        )
        .subcommand(
            Command::new("unratelimit")
                .about("Remove user ratelimit")
                .arg(
                    Arg::new("user_id")
                    .long("user")
                    .short('u')
                    .takes_value(true)
                    .required(true)
                    .help("user identifier")
                )
        )
        .subcommand(
            Command::new("isavailable")
                .about("Check if username is available, and valid, for the server")
                .arg(
                    Arg::new("username")
                    .long("name")
                    .short('n')
                    .takes_value(true)
                    .required(true)
                    .help("username localpart")
                )
        )
        .subcommand(
            Command::new("login")
                .about("Get an access token that can be used to authenticate as that user")
                .arg(
                    Arg::new("user_id")
                    .long("user")
                    .short('u')
                    .takes_value(true)
                    .required(true)
                    .help("user identifier")
                )
        )
}
